# platform_rules.py
# ALL platform rules extracted from OTT Clients Protocol Excel images
# This is the single source of truth for all platform-specific rules

PLATFORMS = {

    "discovery_max": {
        "name": "Discovery Max V2",
        "max_chars_per_line": 37,
        "max_chars_italics": 36,
        "max_lines": 2,
        "min_duration_seconds": 1.08,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "reading_speed_target_cps": 15,
        "reading_speed_max_cps": 21,
        "reading_speed_yellow_threshold": 15,
        "fps": 25,  # PAL
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",  # -Speaker1\n-Speaker2
        "profanity_format": "xxx",  # fxxx, cxxx etc
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "rules": [
            "Maximum 37 characters per line (36 for italics)",
            "Maximum 2 lines per subtitle",
            "Only one speaker per line",
            "Minimum duration: 1.08 seconds (GTS profile set to 1.08s)",
            "Maximum duration: 7 seconds",
            "Target reading speed: 15 CPS. Yellow subtitles allowed",
            "Maximum reading speed: 21 CPS — cannot be crossed (marked red)",
            "Max 5 red reading speed subtitles per file",
            "Minimum interval between subtitles: 0.02 seconds",
            "Two speakers: begin each line with hyphen without space (-Speaker)",
            "Use double hyphens (--) for interrupted sentences",
            "Use ellipses (...) for trail offs and long pauses",
            "Avoid double punctuation marks (!?, !!)",
            "Always use quotation marks instead of apostrophes for quotes",
            "Numbers 1-10 in words, above 10 numerically",
            "Song titles in quotation marks, song lyrics in italics",
            "Subtitles positioned bottom, centre-justified",
            "Raise subtitle above on-screen text or to top if covers face/mouth",
            "For beeped profanity use asterisks (****)",
            "End credit: add 'Subtitling by Iyuno' at start of credits roll (2-4 secs)",
        ],
        "remove_elements": ["HOH", "EMT", "stage_directions", "character_names",
                           "scene_descriptions", "slang_notes"],
    },

    "discovery_scripps": {
        "name": "Discovery Scripps Network (SNI)",
        "max_chars_per_line": 36,
        "max_lines": 2,
        "min_duration_seconds": 0.12,
        "max_duration_seconds": 6.0,
        "min_interval_seconds": 0.02,
        "reading_speed_target_cps": 15,
        "reading_speed_max_cps": 21,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "profanity_format": "bleep_asterisk",  # *bleep*
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "sub_channels": [
            "Discovery Channel (DC)", "DC-Animal Planet", "DC-Kids",
            "DC-Kids HD", "DC-Animal Planet HD", "DC HD",
            "Scripps Network", "Travel Channel", "HGTV",
            "Food Network", "AFC (Asian Food Channel)"
        ],
        "rules": [
            "Maximum 36 characters per line",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 0.12 seconds",
            "Maximum duration: 6 seconds",
            "3 frames header, 5 frames tail",
            "Subtitles timed to audio or within 3 frames of audio",
            "Two speakers: hyphen without space on each line",
            "For beeped audio: indicate as *bleep* (capital B if starts sentence: *Bleep*)",
            "Do not use &, <, >, degree or copyright symbols in EN2 files",
            "No text styles (italics, bold, underline, colour) in EN2 files",
            "Spell out numbers 1-9 if starting sentence (except year/addresses)",
            "Above 9 write as digit, comma for numbers above 999",
            "No need to respect shot/scene changes at cue-in and cue-out",
            "First subtitle must not be cued within first 1 second of programme",
            "Do not subtitle English burn-ins when already burnt in English on screen",
        ],
        "remove_elements": ["stage_directions", "character_names", "scene_descriptions",
                           "slang_notes", "foreign_language_untranslated"],
    },

    "nickelodeon": {
        "name": "Nickelodeon V10",
        "max_chars_per_line": 42,  # Template
        "max_chars_eng_sub": 27,   # English Subtitle
        "max_lines": 2,
        "min_duration_seconds": 0.21,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "rules": [
            "Maximum 42 characters per line (template), 27 characters (English subtitle)",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 0.21 seconds",
            "Maximum duration: 7 seconds",
            "Two speakers: hyphen without space on each line",
            "No italics for songs, voices over phone, TV, radio or narrator",
            "For Make It Pop titles: disregard opening and end songs",
            "Do not capitalise second line of song lyrics if continuation of first",
            "Spell out numbers 1-9 if starting sentence",
            "Raise single line subtitle max 3-4 lines",
            "Raise double line subtitle max 2-3 lines",
            "Create a repo file for repositioning",
            "Create an end credit file",
            "All songs and singing segments should be spotted",
        ],
        "remove_elements": ["stage_directions", "character_names", "scene_descriptions",
                           "slang_notes"],
    },

    "disney": {
        "name": "Disney V38",
        "max_chars_per_line": 42,
        "max_lines": 2,
        "min_duration_seconds": 1.0,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "rules": [
            "Maximum 42 characters per line",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 1 second (PAL and VOD)",
            "Maximum duration: 7 seconds",
            "2-3 frames header, 2-3 frames tail",
            "Two speakers: hyphen without space on each line",
            "Numbers 0-9 written out, above 9 numerically",
            "Use ellipses to indicate pause within sentence or dialogue trail off",
            "Use ellipsis without space at start if subtitle starts mid-sentence (...was told)",
            "Song lyrics italicised — no reverse italics in songs",
            "Each lyric starts and ends with music icon ♪ with one space",
            "Non-original songs never included in subtitle files",
            "End credit songs not included in non-hearing impaired files",
            "Italics for: narration/VO, phone calls, foreign terms, radio/TV sound, singing",
            "Off-camera dialogue NOT considered voiceover — use normal type",
            "Character identifiers only for CC/SDH — not standard subtitles",
            "Translator credit: 'Translated by [Name]' — 2 seconds duration",
            "Do not subtitle the Disney+ title",
            "No periods for acronyms: FBI, NASA, NATO",
            "Double hyphens (--) for abrupt interruptions",
            "Raise to top or bottom for positioning",
        ],
        "profanity_rules": {
            "NC17_R_TVMA": "no_check",
            "PG13_TV14": "report_if_not_in_script",
            "PG_G_TVY_TVG_TVPG": "full_report",
            "replace_words": ["cunt", "shit", "piss", "cock", "tit", "fuck", "ass"],
        },
        "remove_elements": ["stage_directions", "character_names", "scene_descriptions",
                           "slang_notes"],
    },

    "tvb": {
        "name": "TVB V11",
        "max_chars_per_line": 44,
        "max_lines": 2,
        "min_duration_seconds": 0.10,
        "max_duration_seconds": 15.0,  # NOTE: 15 seconds not 7!
        "min_interval_seconds": 0.01,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_with_space",  # - Speaker (with space)
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "rules": [
            "Maximum 44 characters per line — use Word Wrap in GTS (Settings > Word Wrap)",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 0.10 seconds",
            "Maximum duration: 15 seconds (different from other platforms!)",
            "Minimum interval: 0.01 seconds",
            "Two speakers: hyphen WITH space (- Speaker) — different from other platforms",
            "Spell out numbers 1-9 if starting sentence",
            "Subtitle all burn-in captions even when there is dialogue",
            "Max ONE LINE when there are captions present",
            "Main/episode title: ALL CAPS, no punctuation, no quotation marks, one line only",
            "Do not subtitle opening/end songs unless plot pertinent",
            "No italics for songs",
            "For profanity (bleeped): nexxx, fxxxhead, fxxxers, fxxxin'",
            "If bleep unclear and no script reference: use ellipsis (...)",
            "Make sure subtitles are 44 characters in ONE line where possible",
        ],
        "remove_elements": ["stage_directions", "character_names", "scene_descriptions",
                           "slang_notes"],
    },

    "dmax": {
        "name": "DMAX English Subtitling",
        "max_chars_per_line": 37,
        "max_chars_italics": 36,
        "max_lines": 2,
        "min_duration_seconds": 1.08,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "reading_speed_target_cps": 15,
        "reading_speed_max_cps": 21,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "rules": [
            "Maximum 37 characters per line (36 for italics)",
            "Maximum 2 lines per subtitle MAXIMUM",
            "Only one speaker per line",
            "Minimum duration: 1 second (GTS profile set to 1.08 seconds)",
            "Maximum duration: 7 seconds",
            "Target reading speed: 15 CPS",
            "Maximum reading speed: 21 CPS",
            "Raised subtitles allowed: above on-screen text/graphics",
            "Can raise to top if covers speaker's face/mouth",
            "Subtitles can be raised to top throughout end credits",
            "REMOVE all HOH and EMT elements",
        ],
        "remove_elements": ["HOH", "EMT", "stage_directions", "character_names",
                           "scene_descriptions", "slang_notes"],
    },

    "guide_discovery": {
        "name": "Guide Discovery English Subtitling",
        "max_chars_per_line": 37,
        "max_chars_italics": 36,
        "max_lines": 2,
        "min_duration_seconds": 1.08,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "min_frame_gap": 2,
        "reading_speed_target_cps": 15,
        "reading_speed_max_cps": 21,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "zero_subtitle_required": True,
        "file_format": "PAC",
        "file_naming_format": "EHD_123456E_ENG.PAC",
        "rules": [
            "Maximum 37 characters per line (36 for italics)",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 1.08 seconds",
            "Maximum duration: 7 seconds",
            "Minimum gap between subtitles: 2 frames",
            "Reading speed target: 15 CPS / 180 wpm",
            "Maximum reading speed: 21 CPS — never exceed",
            "File naming: EHD_123456E_ENG.PAC — strictly enforced, wrong name = rejection",
            "Zero subtitle required: Show name, Ep, Language, STORY:, LANG: fields",
            "STORY and LANG must be capitalised with colon followed by space",
            "Hyphen between EHD prefix and number (different from file naming)",
            "End credit: 'Subtitling by Iyuno' minimum 2 secs maximum 4 secs",
            "Final clearing caption: last subtitle blank, duration 2 seconds",
            "Timed on speech — if speech within 10-12 frames after shot change, bring on with shot",
            "Two speakers: hyphen without space (-Speaker)",
            "Max 2 speakers per subtitle, 1 speaker per line",
            "Edit out fillers: ugh, hmm, erm, ah, oh",
            "Numbers 1-10 in words, above 10 numerically",
            "Use CAPS sparingly for emphasis",
            "Acronyms without dots: BBC, FBI, CIA",
            "Song lyrics italicised, upper case at beginning of line",
            "No punctuation at end of song line except ? and !",
            "Standard US English spelling",
            "Always run spellcheck before delivery",
            "Spelling out names: J-E-N-N-Y format",
            "Beeped profanity: use asterisks same count as letters (****)",
            "Muted profanity: use ellipsis (...)",
            "Foreign words not in common English: use italics",
            "Do not italicise place names, food, brands, band names",
            "No spaces before punctuation marks",
            "Quotations in double speech marks",
            "Discovery profanity list: fxxx, cxxx, pxxx format",
        ],
        "profanity_table": {
            "bush": "bxxx", "cock": "cxxx", "cocksucker": "cxxxsucker",
            "cocktease": "cxxxtease", "cockteaser": "cxxxteaser",
            "cunt": "cxxx", "fuck": "fxxx", "fucked": "fxxxed",
            "fucking": "fxxxing", "fucks": "fxxxs",
            "motherfucker": "motherfxxx", "pussy": "pxxx",
            "pussyhole": "pxxxhole",
        },
        "remove_elements": ["HOH", "EMT", "stage_directions", "character_names",
                           "scene_descriptions", "slang_notes", "fillers"],
    },

    "vubiquity": {
        "name": "Vubiquity V2",
        "max_chars_per_line": 50,
        "max_lines": 2,
        "min_duration_seconds": 0.21,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "zero_subtitle_required": True,
        "file_format": "PAC",  # Confirmed from GTS Pro screenshot
        "export_style": "DVB",
        "rules": [
            "Maximum 50 characters per line (highest limit of all platforms)",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 0.21 seconds",
            "Maximum duration: 7 seconds",
            "Two speakers: hyphen WITHOUT space (-Speaker)",
            "Spell out numbers 1-9 if starting sentence",
            "Raise subtitle to avoid on-screen text — max 3 lines for single, 2 for double",
            "Create a repo file for repositioning",
            "Create an end credit file",
            "Export as PAC file, DVB style, PAL 25fps",
        ],
        "remove_elements": ["stage_directions", "character_names", "scene_descriptions",
                           "slang_notes"],
    },

    "generic": {
        "name": "Generic / Other",
        "max_chars_per_line": 42,
        "max_lines": 2,
        "min_duration_seconds": 1.0,
        "max_duration_seconds": 7.0,
        "min_interval_seconds": 0.02,
        "fps": 25,
        "venue": "Broadcast",
        "two_speaker_format": "hyphen_no_space",
        "zero_subtitle_required": False,
        "file_format": "SRT",
        "rules": [
            "Maximum 42 characters per line",
            "Maximum 2 lines per subtitle",
            "Minimum duration: 1 second",
            "Maximum duration: 7 seconds",
            "Standard punctuation rules apply",
            "Sentence case throughout",
        ],
        "remove_elements": ["stage_directions", "character_names", "scene_descriptions",
                           "slang_notes"],
    },
}

# Universal SDI House Protocol Guidelines (from Universal_Guidelines.xlsx images)
UNIVERSAL_GUIDELINES = {
    "frame_header": 3,
    "frame_tail": 5,
    "frame_tail_reading_speed_max": 12,
    "min_gap_frames": 2,
    "forbidden_gap_range": (3, 11),  # gaps of 3-11 frames not allowed
    "shot_change_cue_in_window": 12,  # if dialogue starts within 12 frames after shot change
    "shot_change_cue_out_window": 12,  # if out-time within 12 frames before shot change
    "crossing_shot_change": {
        "start_before_1_7_frames": "move_to_first_frame_after_shot_change",
        "start_before_8_11_frames": "move_to_12_frames_before_shot_change",
        "end_after_1_7_frames": "move_to_2_frames_before_shot_change",
        "end_after_8_11_frames": "keep_12_frames_after_shot_change",
    },
    "rules": [
        "3 frame header, 5 frame tail (add up to 12 frame tail for reading speed)",
        "No gaps of 3-11 frames between subtitles — must be 2 frames or 12+ frames",
        "Close gaps by extending out-time of previous subtitle",
        "If speech starts on/within 12 frames after shot change — cue in at shot change",
        "If out-time within 12 frames before shot change — extend to shot change",
        "Dialogue starting 1-7 frames before shot change — start on 1st frame after shot change",
        "Dialogue starting 8-11 frames before shot change — start 12 frames before shot change",
        "Dialogue ending 1-7 frames after shot change — end 2 frames before shot change",
        "Dialogue ending 8-11 frames after shot change — end 12 frames after shot change",
    ]
}


def get_platform(platform_key: str) -> dict:
    return PLATFORMS.get(platform_key, PLATFORMS["generic"])


def get_platform_list() -> list:
    return [
        {"key": k, "name": v["name"], "max_chars": v["max_chars_per_line"],
         "max_lines": v["max_lines"], "file_format": v.get("file_format", "PAC"),
         "is_custom": False}
        for k, v in PLATFORMS.items()
    ]


def get_profanity_table(platform_key: str) -> dict:
    p = PLATFORMS.get(platform_key, {})
    return p.get("profanity_table", {})
